# @package _global_

train_fn: agent.dqn.main
name: dqn
total_timesteps: 5000000
learning_rate: 0.00025
num_envs: 1
buffer_size: 10000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
batch_size: 128
start_e: 1.0
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000
train_frequency: 10
eval_episodes: 10
eval_freq: 1000