wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716695877
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 50
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 50
      - 55
      3:
      - 13
      - 15
      - 23
      4: 3.8.0
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
