train_fn: algorithms.cmaes.train
name: cmaes

init_stdev: 0.1
pop_size: 1024
num_elites: 512

episodes_for_fitness: 1

num_steps: 3000

eval_episodes: 128
eval_interval: 10

policy_network:
  hidden_layer_sizes: [16, 16]
